jobs:
  build:
    docker:
      - image: cimg/node:12.16
    steps:
      - checkout
      # Uncomment below and set the key to point to the proper file
      - restore_cache:
          name: Restore Yarn Package Json Cache
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1- 
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Json Cache
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      

workflows:
  version: 2
  cache-save-and-restore:
    jobs:
      - build